name: 'static'
description: 'Use GitHub Actions to deploy your static.json microsite'
author: 'static'

branding:
  icon: 'layout'
  color: 'gray-dark'

inputs:
  path:
    description: 'The path to your static.json configuration'
    required: true
    default: 'static.json'

runs:
  using: node20
  main: dist/index.js
